DROP TABLE IF EXISTS users_DB;

CREATE TABLE users_DB (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(100) NOT NULL DEFAULT '',
    last_name VARCHAR(100) NOT NULL DEFAULT '',
    email VARCHAR(100) NOT NULL DEFAULT '',
    age INT NOT NULL DEFAULT 0,
    address VARCHAR(100) NOT NULL DEFAULT,
    joining_date DATE NOT NULL DEFAULT CURRENT_DATE
);